# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_frontend', models.BooleanField(default=True, verbose_name='前台权限')),
                ('has_backend', models.BooleanField(default=False, verbose_name='后台权限')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='分组')),
            ],
            options={
                'verbose_name': '角色管理',
                'verbose_name_plural': '角色管理',
                'db_table': 'role',
            },
        ),
    ]
