# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180320_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='has_cycle_task',
            field=models.BooleanField(default=False, verbose_name='任务管理'),
        ),
    ]
