# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0002_auto_20180306_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
            ],
            options={
                'verbose_name': '模块管理',
                'verbose_name_plural': '模块管理',
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('module', models.ManyToManyField(to='terminology.Module', verbose_name='包含模块')),
            ],
            options={
                'verbose_name': '平台管理',
                'verbose_name_plural': '平台管理',
                'db_table': 'platform',
            },
        ),
    ]
