# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0004_auto_20180329_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('name', 'platform')]),
        ),
    ]
