# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0006_auto_20180503_1042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([]),
        ),
    ]
