# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='可否使用')),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='script.Script', verbose_name='对应脚本')),
            ],
            options={
                'verbose_name': '类别管理',
                'verbose_name_plural': '类别管理',
                'db_table': 'problem_cla',
            },
        ),
    ]
