# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem_classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemcla',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='problemcla',
            name='script',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='script.Script', verbose_name='对应脚本'),
        ),
    ]
