# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem_classification', '0003_problemcla_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemcla',
            name='script',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='script.Script', verbose_name='对应脚本'),
        ),
    ]
