# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('page', models.CharField(help_text='dashboard0, dashboard1, dashboard2', max_length=50, verbose_name='属于哪个页面')),
                ('slice_id', models.PositiveIntegerField(verbose_name='每个slice的id')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('i', models.CharField(max_length=50)),
                ('chart_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '前端展示用图表位置',
                'verbose_name_plural': '前端展示用图表位置',
                'db_table': 'frontend_layout',
            },
        ),
    ]
