# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-08 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_frontendlayout_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontendlayout',
            name='slice_id',
        ),
        migrations.AlterField(
            model_name='frontendlayout',
            name='page',
            field=models.PositiveSmallIntegerField(help_text='dashboard0, dashboard1, dashboard2', max_length=50, verbose_name='属于哪个页面'),
        ),
    ]
