# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_auto_20180408_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendlayout',
            name='x_field',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='frontendlayout',
            name='x_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='frontendlayout',
            name='y_field',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='frontendlayout',
            name='y_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='frontendlayout',
            name='y_unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
