# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminology', '0001_initial'),
        ('problem_classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('jira_code', models.CharField(max_length=100, verbose_name='jira键值')),
                ('tackle_status', models.BooleanField(default=False, help_text='0未修复 1已修复，应根据end自动变', verbose_name='处理状态')),
                ('level', models.PositiveSmallIntegerField(verbose_name='问题平级')),
                ('description', models.CharField(default='', max_length=400, verbose_name='问题描述')),
                ('start_time', models.DateTimeField(verbose_name='jira创建日期')),
                ('end_time', models.DateTimeField(null=True, verbose_name='jira完成日期')),
                ('process_time', models.PositiveIntegerField(default=-1, help_text='单位是分钟，应在有end时计算', verbose_name='处理时长')),
                ('reporter', models.CharField(max_length=10, verbose_name='jira报告人')),
                ('handler', models.CharField(default='', help_text='可能有多个人', max_length=100, verbose_name='处理人')),
                ('influenced_university', models.CharField(default='', max_length=50, verbose_name='影响学校')),
                ('influenced_student', models.CharField(default='', help_text='201233/张三...', max_length=1000, verbose_name='影响用户')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problem_classification.ProblemCla', verbose_name='对应问题分类')),
                ('keywords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='terminology.Terminology', verbose_name='所属关键词')),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='terminology.Terminology', verbose_name='所属模块')),
                ('platforms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='terminology.Terminology', verbose_name='所属平台')),
            ],
            options={
                'verbose_name': '问题管理',
                'verbose_name_plural': '问题管理',
                'db_table': 'problem',
            },
        ),
    ]
