# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='influenced_id',
            field=models.CharField(default='', help_text='201233...', max_length=1000, verbose_name='影响用户id'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='influenced_student',
            field=models.CharField(default='', help_text='张三...', max_length=1000, verbose_name='影响学生姓名'),
        ),
    ]
