# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 11:47
from __future__ import unicode_literals

import common.modelbase
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0002_auto_20180306_0841'),
        ('problem_classification', '0002_auto_20180306_0918'),
        ('problem', '0003_auto_20180312_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInJira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, null=True, verbose_name='用户姓名')),
                ('is_inner', models.BooleanField(default=True, verbose_name='是否是内部员工')),
                ('stu_num', common.modelbase.PositiveBigIntegerField(null=True, verbose_name='jira中的问题学生的学号')),
            ],
            options={
                'verbose_name': '姓名管理',
                'verbose_name_plural': '姓名管理',
                'db_table': 'user_in_jira',
            },
        ),
        migrations.RemoveField(
            model_name='problem',
            name='classification',
        ),
        migrations.AddField(
            model_name='problem',
            name='classification',
            field=models.ManyToManyField(to='problem_classification.ProblemCla', verbose_name='对应问题分类'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='handler',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='influenced_id',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='influenced_student',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='keywords',
        ),
        migrations.AddField(
            model_name='problem',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', to='terminology.Terminology', verbose_name='所属关键词'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='modules',
        ),
        migrations.AddField(
            model_name='problem',
            name='modules',
            field=models.ManyToManyField(related_name='modules', to='terminology.Terminology', verbose_name='所属模块'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='platforms',
        ),
        migrations.AddField(
            model_name='problem',
            name='platforms',
            field=models.ManyToManyField(related_name='platform', to='terminology.Terminology', verbose_name='所属平台'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='reporter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='problem.UserInJira', verbose_name='jira报告人'),
        ),
        migrations.AddField(
            model_name='problem',
            name='handler',
            field=models.ManyToManyField(help_text='可能有多个人', related_name='handler', to='problem.UserInJira', verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='problem',
            name='influenced_id',
            field=models.ManyToManyField(related_name='influenced_id', to='problem.UserInJira', verbose_name='影响用户id'),
        ),
        migrations.AddField(
            model_name='problem',
            name='influenced_student',
            field=models.ManyToManyField(related_name='influenced_student', to='problem.UserInJira', verbose_name='影响学生姓名'),
        ),
    ]
