# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20180323_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='problem',
            name='modules',
            field=models.ManyToManyField(related_name='modules', to='terminology.Module', verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='platforms',
            field=models.ManyToManyField(related_name='platform', to='terminology.Platform', verbose_name='所属平台'),
        ),
    ]
