# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20180323_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='process_time',
            field=models.PositiveIntegerField(default=-1, help_text='单位是分钟，应在有end时计算', null=True, verbose_name='处理时长'),
        ),
    ]
