# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_auto_20180323_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pm',
            field=models.CharField(max_length=10, null=True, verbose_name='产品负责人'),
        ),
        migrations.AddField(
            model_name='problem',
            name='rdm',
            field=models.CharField(max_length=10, null=True, verbose_name='研发负责人'),
        ),
    ]
