# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_auto_20180323_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='jira_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='jira键值'),
        ),
    ]
