# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_auto_20180323_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinjira',
            name='is_inner',
        ),
        migrations.RemoveField(
            model_name='userinjira',
            name='stu_num',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='handler',
        ),
        migrations.AddField(
            model_name='problem',
            name='handler',
            field=models.ManyToManyField(help_text='可能有多个人', related_name='handler', to='problem.UserInJira', verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='reporter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='problem.UserInJira', verbose_name='jira报告人'),
        ),
        migrations.AlterField(
            model_name='userinjira',
            name='username',
            field=models.CharField(default='a', max_length=10, unique=True, verbose_name='用户姓名'),
            preserve_default=False,
        ),
    ]
