# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_auto_20180325_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityInJira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='学校名称')),
            ],
            options={
                'verbose_name': '校名管理',
                'verbose_name_plural': '校名管理',
                'db_table': 'university',
            },
        ),
        migrations.AlterField(
            model_name='problem',
            name='pm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm', to='problem.UserInJira', verbose_name='产品负责人'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rdm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdm', to='problem.UserInJira', verbose_name='研发负责人'),
        ),
    ]
