# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_auto_20180325_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='process_time',
            field=models.FloatField(default=0, help_text='单位是小时，应在有end_time时计算', null=True, verbose_name='处理时长'),
        ),
    ]
