# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_auto_20180328_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='problem.UserInJira', verbose_name='jira报告人'),
        ),
    ]
