# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0017_auto_20180328_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='pm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm', to='problem.UserInJira', verbose_name='产品负责人'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rdm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdm', to='problem.UserInJira', verbose_name='研发负责人'),
        ),
    ]
