# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0019_auto_20180328_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='influenced_university',
            field=models.ManyToManyField(related_name='influenced_university', to='problem.UniversityInJira', verbose_name='影响学校'),
        ),
    ]
