# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('path', models.CharField(default='', help_text='脚本存储路径', max_length=100, verbose_name='路径')),
                ('run_command', models.CharField(default='', help_text='脚本启动命令', max_length=100, verbose_name='命令')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
            ],
            options={
                'verbose_name': '脚本管理',
                'verbose_name_plural': '脚本管理',
                'db_table': 'script',
            },
        ),
    ]
