# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_script_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='name',
            field=models.CharField(default='a.py', max_length=50, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='script',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, help_text='执行脚本的个数', verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='script',
            name='path',
            field=models.CharField(help_text='脚本存储路径', max_length=100, verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='script',
            name='run_command',
            field=models.CharField(help_text='脚本启动命令', max_length=100, verbose_name='命令'),
        ),
    ]
