# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0004_auto_20180316_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, help_text='执行脚本的个数', verbose_name='数量'),
        ),
    ]
