# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem_classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('cycle', models.PositiveIntegerField(default=0, help_text='单位是分钟', verbose_name='执行周期')),
                ('start_time', models.DateTimeField(null=True, verbose_name='启动时间')),
                ('status', models.CharField(default='未启动', help_text='未启动、运行中、成功、失败', max_length=10, verbose_name='运行状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='可否启用')),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problem_classification.ProblemCla', verbose_name='对应问题分类')),
            ],
            options={
                'verbose_name': '脚本管理',
                'verbose_name_plural': '脚本管理',
                'db_table': 'cycle_task',
            },
        ),
    ]
