# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletask',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_classification.ProblemCla', verbose_name='对应问题分类'),
        ),
    ]
