# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_task', '0002_auto_20180312_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletask',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='备注信息'),
        ),
        migrations.AddField(
            model_name='cycletask',
            name='next_time',
            field=models.DateTimeField(help_text='每次根据执行周期刷新', null=True, verbose_name='下一次执行的时间'),
        ),
        migrations.AlterField(
            model_name='cycletask',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
