# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_task', '0003_auto_20180328_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletask',
            name='count',
            field=models.PositiveIntegerField(default=0, help_text='只是自己记下执行的次数', verbose_name='执行次数'),
        ),
        migrations.AlterField(
            model_name='cycletask',
            name='cycle',
            field=models.PositiveIntegerField(default=0, help_text='单位是小时', verbose_name='执行周期'),
        ),
        migrations.AlterField(
            model_name='cycletask',
            name='description',
            field=models.CharField(default='', max_length=400, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='cycletask',
            name='next_time',
            field=models.DateTimeField(null=True, help_text='每次根据执行周期刷新，执行失败时设空', verbose_name='下一次执行的时间'),
        ),
        migrations.AlterField(
            model_name='cycletask',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='启动时间'),
        ),
    ]
