# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_task', '0005_auto_20180328_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletask',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
    ]
