# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_task', '0006_auto_20180328_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletask',
            name='status',
            field=models.CharField(default='停止', help_text='停止、正常、失败', max_length=10, verbose_name='运行状态'),
        ),
    ]
