# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem_classification', '0005_auto_20180315_1120'),
        ('script', '0005_auto_20180316_1745'),
        ('cycle_task', '0007_auto_20180328_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('pid', models.PositiveIntegerField(default=0, verbose_name='执行脚本的进程id')),
                ('result', models.TextField(default={}, verbose_name='脚本返回值')),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problem_classification.ProblemCla', verbose_name='对应问题分类')),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='script.Script', verbose_name='对应脚本')),
            ],
            options={
                'verbose_name': '脚本返回结果',
                'verbose_name_plural': '脚本返回结果',
                'db_table': 'cycle_task_result',
            },
        ),
    ]
