# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_task', '0008_cycletaskresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletask',
            name='pid',
            field=models.PositiveIntegerField(default=0, verbose_name='执行脚本的进程id'),
        ),
        migrations.AddField(
            model_name='cycletask',
            name='result',
            field=models.TextField(default={}, verbose_name='脚本返回值'),
        ),
    ]
