# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_task', '0009_auto_20180403_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletask',
            name='pid',
            field=models.IntegerField(default=-1, verbose_name='执行脚本的进程id'),
        ),
    ]
