# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_task', '0011_auto_20180403_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycletaskresult',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='cycletaskresult',
            name='script',
        ),
        migrations.DeleteModel(
            name='CycleTaskResult',
        ),
    ]
